Adds Semantical Equivalence of Types Validation Rule
graphql/composite-schemas-spec pull request #37
Opened 2024-08-01 18:34 UTC by michaelstaib

2024-08-15 14:06 UTC, glen-84 requested changes

2024-08-15 14:06 UTC, glen-84 commented on cspell.yml
> +  - TYPE_KIND_NOT_MERGABLE
```suggestion
```

2024-08-15 14:06 UTC, glen-84 commented on spec/Section 4 -- Composition.md
> +`TYPE_KIND_NOT_MERGABLE`
```suggestion
`TYPE_KIND_NOT_MERGEABLE`
```

2024-08-15 14:06 UTC, glen-84 commented on spec/Section 4 -- Composition.md
> +#### Semantical Equivalence of Types
```suggestion
#### Semantic Equivalence of Types
```

2024-08-15 14:27 UTC, glen-84 requested changes

2024-08-15 14:27 UTC, glen-84 commented on spec/Section 4 -- Composition.md
> +For the schema schema composition process to be able to merge types with the
```suggestion
For the schema composition process to be able to merge types with the
```

2024-08-15 14:27 UTC, glen-84 commented on spec/Section 4 -- Composition.md
> +However, if the second type would be a scalar type, the types would not be
```suggestion
However, if the second type were a scalar type, the types would not be
```

2024-12-31 14:54 UTC, PascalSenn commented
@michaelstaib  this is already implemented by `TYPE_KIND_MISMATCH` i believe

2024-12-31 18:24 UTC, michaelstaib commented
@PascalSenn close this one if you think its implemented.

2025-06-26 14:24 UTC, closed without merging