Adds Output Field Argument Types Mergable to Composition
graphql/composite-schemas-spec pull request #39
Opened 2024-08-04 15:07 UTC by PascalSenn

2024-08-04 15:26 UTC, glen-84 requested changes

2024-08-04 15:26 UTC, glen-84 commented on spec/Section 4 -- Composition.md
> +  subgraphs with the same name.
Source schemas?

2024-08-04 15:26 UTC, glen-84 commented on spec/Section 4 -- Composition.md
> +- for each {fields} in {fieldsByName}
```suggestion
- For each {fields} in {fieldsByName}
```

2024-08-04 15:26 UTC, glen-84 commented on spec/Section 4 -- Composition.md
> +equivalent and mergeable when they have a mergeable argument types.
```suggestion
equivalent and mergeable when they have mergeable argument types.
```

2024-08-04 15:27 UTC, glen-84 commented
PR title:

```diff
-Adds Output Field Argument Types Mergable to Composition
+Adds Output Field Argument Types Mergeable to Composition
```

2024-11-07 13:12 UTC, michaelstaib commented on spec/Section 4 -- Composition.md
> +  - Let {types} be the set of all types with the name {typeName} from all source
```suggestion
  - Let {types} be the set of all types with the {typeName} from all source
```

2024-12-31 15:04 UTC, PascalSenn commented
Closed by #93

2024-12-31 15:04 UTC, closed without merging