Adds Non Null Input fields cannot be inaccessible
graphql/composite-schemas-spec pull request #40
Opened 2024-08-04 15:30 UTC by PascalSenn

2024-08-04 15:35 UTC, PascalSenn commented
Do we automatically remove a field that references an inaccessible type, or must the field be explicitly declared as inaccessible to avoid a composition error?

2024-08-04 17:49 UTC, PascalSenn commented on spec/Section 4 -- Composition.md
> +
@michaelstaib  should we have a generalised rule for require?

2024-08-04 18:18 UTC, glen-84 requested changes

2024-08-04 18:18 UTC, glen-84 commented on spec/Section 4 -- Composition.md
> +#### Input Fields cannot reference be inaccessible type
```suggestion
#### Input Fields cannot reference inaccessible type
```

2024-08-04 18:18 UTC, glen-84 commented on spec/Section 4 -- Composition.md
> +In a composed schema, a field within a input type must only reference types that are exposed.
```suggestion
In a composed schema, a field within an input type must only reference types that are exposed. 
```

2024-08-04 18:18 UTC, glen-84 commented on spec/Section 4 -- Composition.md
> +
```suggestion
```

2024-12-31 15:23 UTC, PascalSenn commented
Closed by #93

2024-12-31 15:23 UTC, closed without merging