Adds input with differnt fields to composition
graphql/composite-schemas-spec pull request #41
Opened 2024-08-04 17:01 UTC by PascalSenn

2024-08-04 18:27 UTC, glen-84 requested changes

2024-08-04 18:27 UTC, glen-84 commented on spec/Section 4 -- Composition.md
> +This rule ensures that input object types with the same name across different subgraphs have identical sets of field names.
```suggestion
This rule ensures that input object types with the same name across different source schemas have identical sets of field names. 
```

2024-08-04 18:27 UTC, glen-84 commented on spec/Section 4 -- Composition.md
> +Consistency in input object fields across subgraphs is required to avoid conflicts and ambiguities in the composed schema.
```suggestion
Consistency in input object fields across source schemas is required to avoid conflicts and ambiguities in the composed schema.
```

2024-08-04 18:27 UTC, glen-84 commented on spec/Section 4 -- Composition.md
> +When an input object is defined with differing fields across subgraphs, it can lead to issues in query execution.
```suggestion
When an input object is defined with differing fields across source schemas, it can lead to issues in query execution. 
```

2024-08-04 18:27 UTC, glen-84 commented on spec/Section 4 -- Composition.md
> +A field expected in one subgraph might be absent in another, leading to undefined behavior.
```suggestion
A field expected in one source schema might be absent in another, leading to undefined behavior.
```

2024-08-04 18:27 UTC, glen-84 commented on spec/Section 4 -- Composition.md
> +This rule prevents such inconsistencies by enforcing that all instances of the same named input object across subgraphs have a matching set of field names.
```suggestion
This rule prevents such inconsistencies by enforcing that all instances of the same named input object across source schemas have a matching set of field names.
```

2024-08-04 18:27 UTC, glen-84 commented on spec/Section 4 -- Composition.md
> +In this example, both subgraphs define `Input1` with the same field `field1`, satisfying the rule:
```suggestion
In this example, both source schemas define `Input1` with the same field `field1`, satisfying the rule:
```

2024-08-04 18:27 UTC, glen-84 commented on spec/Section 4 -- Composition.md
> +
```suggestion
```

2024-08-08 16:53 UTC, michaelstaib commented
```graphql
# warning

input Input1 {
  field1: String
}

input Input1 {
  field2: String
}

# error

input Input1 {
  field1: String!
}

input Input1 {
  field2: String
}
```

2024-11-10 10:10 UTC, glen-84 requested changes

2024-11-10 10:10 UTC, glen-84 commented on spec/Section 4 -- Composition.md
> +  - Let `{inputFields}` be the set of all field names in of required fields in `{input}`.
```suggestion
  - Let `{inputFields}` be the set of all field names of required fields in `{input}`.
```

2024-11-10 10:10 UTC, glen-84 commented on spec/Section 4 -- Composition.md
> +This rule ensures that input object types with the same name across different subgraphs share a consistent set of required fields.
Are we reverting to "subgraph" naming again?

2024-12-31 14:53 UTC, PascalSenn commented
closed by #93

2024-12-31 14:53 UTC, closed without merging