Adds empty merged input object type to composition
graphql/composite-schemas-spec pull request #44
Opened 2024-08-04 18:49 UTC by PascalSenn

2024-08-04 18:50 UTC, PascalSenn commented on spec/Section 4 -- Composition.md
> +
TODO: Exlude required fields

2024-08-05 17:52 UTC, glen-84 requested changes

2024-08-05 17:52 UTC, glen-84 commented on spec/Section 4 -- Composition.md
> +- Let {inputs} be the set of all input object in the merged schema
```suggestion
- Let {inputs} be the set of all input objects in the merged schema
```

2024-08-05 17:52 UTC, glen-84 commented on spec/Section 4 -- Composition.md
> +`@inaccessible` in at least on of the schemas:
```suggestion
`@inaccessible` in at least one of the schemas:
```

2024-12-31 14:09 UTC, PascalSenn commented
closed by #93

2024-12-31 14:09 UTC, closed without merging