Adds Input Field Types mergeable validation rule
graphql/composite-schemas-spec pull request #45
Opened 2024-08-06 12:34 UTC by michaelstaib

2024-08-06 18:19 UTC, glen-84 requested changes

2024-08-06 18:19 UTC, glen-84 commented on spec/Section 4 -- Composition.md
> +`INPUT_FIELD_TYPES_MERGABLE`
```suggestion
`INPUT_FIELD_TYPES_NOT_MERGEABLE`
```

2024-08-06 18:19 UTC, glen-84 commented on spec/Section 4 -- Composition.md
> +  - if {InputFieldsAremergeable(fields)} must be true.
```suggestion
  - {InputFieldsAreMergeable(fields)} must be true.
```

2024-08-06 18:19 UTC, glen-84 commented on spec/Section 4 -- Composition.md
> +InputFieldsAremergeable(fields):
```suggestion
InputFieldsAreMergeable(fields):
```

2024-08-06 18:19 UTC, glen-84 commented on spec/Section 4 -- Composition.md
> +Fields are also consodered mergable if they have different nullability defined
```suggestion
Fields are also considered mergeable if they have different nullability defined.
```

2024-08-06 18:19 UTC, glen-84 commented on spec/Section 4 -- Composition.md
> +across Here, the field `tags` in `Input1` is a list type with compatible inner
```suggestion

Here, the field `tags` in `Input1` is a list type with compatible inner
```

2024-08-06 18:19 UTC, glen-84 commented on spec/Section 4 -- Composition.md
> +(`String` and `DateTime`), making them not mergeable:
```suggestion
(`String` and `DateTime`), making them non-mergeable:
```

2024-08-08 07:59 UTC, glen-84 commented on spec/Section 4 -- Composition.md
> +different named types across (`String` and `DateTime`) source schemas:
```suggestion
In this example, the field `field` on `Input1` is not mergeable as the field has
different named types (`String` and `DateTime`) across source schemas:
```

2024-08-08 16:32 UTC, michaelstaib commented
We need to explain how the nullability merges ...

2024-08-08 16:34 UTC, michaelstaib commented on spec/Section 4 -- Composition.md
> +  - {SameTypeShape(typeA, typeB)} must be true.
this is wrong

2024-12-31 13:52 UTC, PascalSenn commented on spec/Section 4 -- Composition.md
> +  - {SameTypeShape(typeA, typeB)} must be true.
Resolved in 6564626

2024-12-31 13:53 UTC, PascalSenn commented
Closed by #93

2024-12-31 13:53 UTC, closed without merging