Adds validation rule `@lookup` should have nullable return type
graphql/composite-schemas-spec pull request #55
Opened 2024-10-03 15:45 UTC by PascalSenn

2024-10-03 15:59 UTC, glen-84 requested changes

2024-10-03 15:59 UTC, glen-84 commented on spec/Section 4 -- Composition.md
> +In a distributed system, it is likely that some entities are not be found on other subgraphs, even when those subgraphs contribute fields to the type.
```suggestion
In a distributed system, it is likely that some entities will not be found on other subgraphs, even when those subgraphs contribute fields to the type. 
```

2024-10-03 15:59 UTC, glen-84 commented on spec/Section 4 -- Composition.md
> +This counter-example demonstrates a invalid usage:
```suggestion
This counter-example demonstrates invalid usage:
```

2024-12-31 13:29 UTC, PascalSenn commented
Closed by #93

2024-12-31 13:29 UTC, closed without merging