Adds @inaccessible directive
graphql/composite-schemas-spec pull request #59
Opened 2024-11-07 15:54 UTC by michaelstaib

2024-11-10 11:03 UTC, glen-84 requested changes

2024-11-10 11:03 UTC, glen-84 commented on spec/Section 2 -- Source Schema.md
> +The above example removes the field `internalProductById` and the type `Product`
```suggestion
The example below removes the field `internalProductById` and the type `Product`
```

2024-11-10 11:03 UTC, glen-84 commented on spec/Section 2 -- Source Schema.md
> +inaccessible can still be used within the composite execution schema to fulfill
```suggestion
inaccessible can still be used within the composite execution schema to fulfil
```

2024-11-14 18:10 UTC, glen-84 commented
Apologies Michael, `fulfill` is correct for American English. 🤦‍♂️

2024-12-31 14:41 UTC, michaelstaib commented on spec/Section 2 -- Source Schema.md
> +This directive is particularly useful for restricting access to fields or
```suggestion
This directive is useful for restricting access to fields or
```

2024-12-31 14:42 UTC, michaelstaib commented on spec/Section 2 -- Source Schema.md
> +still be used within the composite execution schema to fulfill requirements or
```suggestion
still be used within the _execution schema_ to fulfill requirements or
```

2024-12-31 14:43 UTC, michaelstaib commented on spec/Section 2 -- Source Schema.md
> +still be used within the _execution schema_ to fulfill requirements or
```suggestion
still be used within the _execution schema_ to fulfil requirements or
```

2024-12-31 14:43 UTC, michaelstaib commented on spec/Section 2 -- Source Schema.md
> +In contrast to the `@internal` directive the `@inaccessible` directive hides a
```suggestion
In contrast to the `@internal` directive the `@inaccessible` hides a
```

2024-12-31 14:44 UTC, michaelstaib commented on spec/Section 2 -- Source Schema.md
> +In contrast to the `@internal` directive the `@inaccessible` hides a
```suggestion
In contrast to the `@internal` directive `@inaccessible` hides a
```

2024-12-31 14:44 UTC, michaelstaib commented on spec/Section 2 -- Source Schema.md
> +type member from the composite schema even if other source schemas on the same type
```suggestion
type or output field from the composite schema even if other source schemas on the same type
```

2024-12-31 14:45 UTC, michaelstaib commented on spec/Section 2 -- Source Schema.md
> +system member have no `@inaccessible` directive.
```suggestion
type or output field from the composite schema even if other source schemas on the
same type or output field have no `@inaccessible` directive.
```

2024-12-31 14:55 UTC, merged